### PR TITLE
resizable honored in handles

### PR DESCRIPTION
**Pull request by timmaffett**
This PR makes the controller's `resizable` setting honored when deciding if the resize handles should be created for the `TransformableBox`.
This seems like the desired behavior vs. having resize corner/side controls that do nothing but change the mouse cursor, which is confusing to the user.

ie.  When `resizable` setting for the controller is set to false then the TransformableBox stops making all of the resize corner/side controls.

### CODE REVIEW

**Comment by BirjuVachhani** [comment]
Hi @timmaffett, Thank you for opening this issue.

The intention here was to make handle visibility explicit to the developer. The developer may not want to hide them when it is not resizable. That's why setting `resizable` doesn't hide them. 

For example, this can be used in a crop image screen/dialog where the user makes adjustments and then hits the crop button. Now, its cropping and it may take a while so you don't want the user to be able to resize it anymore but you also don't wanna hide the handles of anything. It just ignores interactions.

To hide handles, you can override handle builder and just return `SizedBox.shrink()` to make them invisible. 

To keep this explicit, we can add another flag something like `hideHandlesWhenNotResizable` that hides the handles when it is not resizable.

**Comment by timmaffett** [comment]
I love the idea of adding another flag such as `hideHandlesWhenNotResizable` which allows the user to explicitly request the behavior. 

I understand that there is the option to override the handle builder, but I think the flag would be preferable for many users so they are not forced to override the handle builder, which is much more complex/lower level coding than just passing an optional `hideHandlesWhenNotResizable` flag to the constructor.

I will add a new PR to include this option, as well as a control to toggle it within the example.
(it accidentally made the changes on a new branch, so a new PR is easier than modifying this one)

I also modified the example code to have the option of including a second box to resize - as the previous example has it's model/code kind of 'hard coded' to control only a single box.

**Comment by BirjuVachhani** [comment]
@timmaffett Should close this PR then?

**Comment by timmaffett** [comment]
Closing this because it is replaced with PR #5

**Pull request closed without merging**
